Remove flake8 validation and add black instead
Add a `checks` job in workflow to do a preliminary checks

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -9,7 +9,31 @@ on:
   schedule:
     - cron: "0 1 * * *"
 jobs:
-  test:
+  checks:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Set up Python 3.8
+        uses: actions/setup-python@v1
+        with:
+          python-version: 3.8
+      - name: Checkout code
+        uses: actions/checkout@v2
+      - name: Install dependencies
+        run: |
+          python -m pip install --upgrade pip
+          pip install ".[dev]"
+      - name: Format with black
+        run: |
+          if ! RES=$(black --check $(git diff --name-only --diff-filter=AM master -- "*.py") 2>&1); then
+            RES="${RES//'%'/'%25'}"
+            RES="${RES//$'\n'/'%0A'}"
+            RES="${RES//$'\r'/'%0D'}"
+            echo "::error ::${RES}"
+            exit 1
+          fi
+          echo ${RES}
+  unit-tests:
+    needs: checks
     runs-on: ubuntu-latest
     strategy:
       matrix:
@@ -24,7 +48,7 @@ jobs:
       - name: Install dependencies
         run: |
           python -m pip install --upgrade pip
-          pip install ".[dev]"
+          pip install ".[test]"
       - name: Test with inv
         run: inv cover qa
       - name: Coveralls
@@ -35,7 +59,7 @@ jobs:
         env:
           COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
   bench:
-    needs: test
+    needs: unit-tests
     runs-on: ubuntu-latest
     if: github.event_name == 'pull_request'
     steps:
